#!/bin/sh

# REQUIRE: FILESYSTEMS
# REQUIRE: NETWORKING
# PROVIDE: unifi

. /etc/rc.subr

name="unifi"
rcvar=`set_rcvar`
start_cmd="unifi_start"
stop_cmd="unifi_stop"

pidfile="/var/run/${name}.pid"

load_rc_config $name

unifi_start()
{
  if checkyesno ${rcvar}; then
    echo "Starting UniFi controller. "

    # The process will run until it is terminated and does not fork on its own.
    # So we start it in the background and stash the pid:
    /usr/local/bin/java -jar /usr/local/UniFi/lib/ace.jar start &
    echo $! > $pidfile

  fi
}

unifi_stop()
{

  if [ -f $pidfile ]; then

    echo -n "Signaling the UniFi controller to stop..."

    # This process does take a while, but the stop command finishes before
    # the service is actually stopped. So we start it in the background:
    /usr/local/bin/java -jar /usr/local/UniFi/lib/ace.jar stop &

    # Get the pid of the stopper:
    stopper=$!

    # Wait until the stopper finishes:
    while [ `pgrep $stopper` ]; do
      echo -n "."
      sleep 3
    done

    echo " acknowledged."
    echo -n "Waiting for the UniFi controller to stop..."

    # ...then we wait until the service identified by the pid file goes away:
    while [ `pgrep -F $pidfile` ]; do
      echo -n "."
      sleep 3
    done

    # Remove the pid file:
    rm $pidfile

    echo " stopped.";
  fi
}

run_rc_command "$1"
