#!/bin/sh

# REQUIRE: FILESYSTEMS
# REQUIRE: NETWORKING
# PROVIDE: unifi

. /etc/rc.subr

name="unifi"
rcvar=`set_rcvar`
start_cmd="unifi_start"
stop_cmd="unifi_stop"

pidfile="/var/run/${name}.pid"

load_rc_config $name

unifi_start()
{
  if checkyesno ${rcvar}; then
    echo "Starting UniFi controller."
    /usr/local/bin/java -jar /usr/local/UniFi/lib/ace.jar start &
    echo $! > $pidfile
  fi
}

unifi_stop()
{

  if [ -f $pidfile ]; then

    echo -n "Stopping UniFi controller."

    /usr/local/bin/java -jar /usr/local/UniFi/lib/ace.jar stop

    while `pgrep -F /var/run/${name}.pid`; do
      echo -n "."
      sleep 3
    done

    rm /var/run/${name}.pid
    echo "done";
    while [ `pgrep -F $pidfile` ]; do
    rm $pidfile
  fi
}

run_rc_command "$1"
